

from graphics import *

def greeting_card():
    win = GraphWin("Greeting Card", 500, 500)
    win.setCoords(0, 0, 50, 50)
    win.setBackground('pink')
    baseheart = Polygon(Point(25, 20), Point(20, 25), Point(25, 30), Point(30, 25))
    hearttop1 = Polygon(Point(20,25),Point(20, 35), Point(25, 30))
    hearttop2 = Polygon(Point(25, 30), Point(30, 35), Point(30, 25))
    baseheart.setOutline('red')
    hearttop1.setOutline('red')
    hearttop2.setOutline('red')
    baseheart.setFill('red')
    hearttop2.setFill('red')
    hearttop1.setFill('red')
    baseheart.draw(win)
    hearttop1.draw(win)
    hearttop2.draw(win)

    valday = Text(Point(25, 15), "Happy Valentine's day")
    valday.draw(win)
    tiparrow = Polygon(Point(40, 40), Point(40, 42), Point(42, 40))
    bottomarrow1 = tiparrow.clone()
    bottomarrow1.move(9, 9)
    bottomarrow2 = bottomarrow1.clone()
    bottomarrow2.move(-.5, -.5)
    arrow = Line(Point(41, 41), Point(50, 50))
    bottomarrow1.setFill('black')
    bottomarrow2.setFill('black')
    tiparrow.setFill('black')
    bottomarrow1.draw(win)
    bottomarrow2.draw(win)
    arrow.draw(win)
    tiparrow.draw(win)
    for frames in range(15):
        bottomarrow1.move(-1,-1)
        bottomarrow2.move(-1,-1)
        arrow.move(-1,-1)
        tiparrow.move(-1, -1)
        time.sleep(.2)
    tiparrow.setFill('red')
    tiparrow.setOutline('red')
    valday.setText("Click anywhere to close")
    win.getMouse()
